[phases.setup]
nixPkgs=["...",ffmpeg]

providers = ["...", "python"]

[phases.build]
cmds = ["pip install -r requirement.txt"]

[phases.start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port 8000
